### ISSUE TITLE
Guard crashes multiple times a day

### ISSUE THREAD

**Issue by Sharma-Rajat** [appscode/guard#190]
Initialize guard with the following parameters:
```sh
    --auth-providers=azure \
    --azure.client-id=spn:REDACTED \
    --azure.tenant-id=spn:REDACTED \
    --azure.client-secret=spn:REDACTED \
    --azure.use-group-uid=false \
    --addr=10.233.0.255:443 \
```
after some time:

```golang
I1018 13:23:38.860208       1 handler.go:31] Received token review request for azure/microsoft
F1018 13:24:32.125926       1 server.go:44] read udp 10.233.102.143:36063->83.168.200.199:123: i/o timeout
goroutine 28 [running]:
github.com/appscode/guard/vendor/github.com/golang/glog.stacks(0xc00037be00, 0xc0005ca140, 0x6b, 0xa0)
        /go/src/github.com/appscode/guard/vendor/github.com/golang/glog/glog.go:766 +0xd4
github.com/appscode/guard/vendor/github.com/golang/glog.(*loggingT).output(0x28706e0, 0xc000000003, 0xc000402e70, 0x27e047e, 0x9, 0x2c, 0x0)
        /go/src/github.com/appscode/guard/vendor/github.com/golang/glog/glog.go:717 +0x306
github.com/appscode/guard/vendor/github.com/golang/glog.(*loggingT).printDepth(0x28706e0, 0xc000000003, 0x1, 0xc0006c2f98, 0x1, 0x1)
        /go/src/github.com/appscode/guard/vendor/github.com/golang/glog/glog.go:646 +0x129
github.com/appscode/guard/vendor/github.com/golang/glog.(*loggingT).print(0x28706e0, 0xc000000003, 0xc0006c2f98, 0x1, 0x1)
        /go/src/github.com/appscode/guard/vendor/github.com/golang/glog/glog.go:637 +0x5a
github.com/appscode/guard/vendor/github.com/golang/glog.Fatal(0xc0006c2f98, 0x1, 0x1)
        /go/src/github.com/appscode/guard/vendor/github.com/golang/glog/glog.go:1125 +0x53
github.com/appscode/guard/server.Server.ListenAndServe.func1(0xc0008a00a0, 0xc0008b70b0)
        /go/src/github.com/appscode/guard/server/server.go:44 +0xe6
created by github.com/appscode/guard/server.Server.ListenAndServe
        /go/src/github.com/appscode/guard/server/server.go:41 +0xc75
```

**Solution:**

I set --clock-check-interval=0

**Comment by nightfury1204** [comment]
@Sharma-Rajat I think you figured out the solution.
Let me know if this fixes the issue for you.
