### ISSUE TITLE
Guard's pod crashing after some time

### ISSUE THREAD

**Issue by rohanmehto2** [appscode/guard#248]
I'm using guard for authentication with external LDAP server. After certain amount of time guard pod crashes and restarts due to an i/o timeout.

```
I0222 21:55:23.923067       1 logs.go:19] FLAG: --alsologtostderr="false"
I0222 21:55:23.923385       1 logs.go:19] FLAG: --analytics="true"
I0222 21:55:23.923400       1 logs.go:19] FLAG: --auth-providers="[ldap]"
I0222 21:55:23.923408       1 logs.go:19] FLAG: --azure.client-id=""
I0222 21:55:23.923412       1 logs.go:19] FLAG: --azure.client-secret=""
I0222 21:55:23.923415       1 logs.go:19] FLAG: --azure.tenant-id=""
I0222 21:55:23.923420       1 logs.go:19] FLAG: --azure.use-group-uid="true"
I0222 21:55:23.923426       1 logs.go:19] FLAG: --clock-check-interval="10m0s"
I0222 21:55:23.923429       1 logs.go:19] FLAG: --github.base-url=""
I0222 21:55:23.923432       1 logs.go:19] FLAG: --gitlab.base-url=""
I0222 21:55:23.923434       1 logs.go:19] FLAG: --google.admin-email=""
I0222 21:55:23.923437       1 logs.go:19] FLAG: --google.sa-json-file=""
I0222 21:55:23.923441       1 logs.go:19] FLAG: --help="false"
I0222 21:55:23.923446       1 logs.go:19] FLAG: --ldap.auth-choice="Simple"
I0222 21:55:23.923452       1 logs.go:19] FLAG: --ldap.bind-dn="cn=admin,dc=example,dc=com"
I0222 21:55:23.923457       1 logs.go:19] FLAG: --ldap.bind-password="password"
I0222 21:55:23.923462       1 logs.go:19] FLAG: --ldap.ca-cert-file=""
I0222 21:55:23.923466       1 logs.go:19] FLAG: --ldap.group-member-attribute="member"
I0222 21:55:23.923470       1 logs.go:19] FLAG: --ldap.group-name-attribute="cn"
I0222 21:55:23.923475       1 logs.go:19] FLAG: --ldap.group-search-dn="ou=Groups,dc=example,dc=com"
I0222 21:55:23.923480       1 logs.go:19] FLAG: --ldap.group-search-filter="(objectClass=groupOfNames)"
I0222 21:55:23.923484       1 logs.go:19] FLAG: --ldap.is-secure-ldap="false"
I0222 21:55:23.923488       1 logs.go:19] FLAG: --ldap.keytab-file=""
I0222 21:55:23.923493       1 logs.go:19] FLAG: --ldap.server-address="192.168.224.23"
I0222 21:55:23.923497       1 logs.go:19] FLAG: --ldap.server-port="389"
I0222 21:55:23.923501       1 logs.go:19] FLAG: --ldap.service-account=""
I0222 21:55:23.923505       1 logs.go:19] FLAG: --ldap.skip-tls-verification="false"
I0222 21:55:23.923510       1 logs.go:19] FLAG: --ldap.start-tls="false"
I0222 21:55:23.923517       1 logs.go:19] FLAG: --ldap.user-attribute="uid"
I0222 21:55:23.923521       1 logs.go:19] FLAG: --ldap.user-search-dn="ou=People,dc=example,dc=com"
I0222 21:55:23.923526       1 logs.go:19] FLAG: --ldap.user-search-filter="(objectClass=person)"
I0222 21:55:23.923534       1 logs.go:19] FLAG: --log_backtrace_at=":0"
I0222 21:55:23.923539       1 logs.go:19] FLAG: --log_dir=""
I0222 21:55:23.923544       1 logs.go:19] FLAG: --logtostderr="false"
I0222 21:55:23.923549       1 logs.go:19] FLAG: --max-clock-skew="2m0s"
I0222 21:55:23.923554       1 logs.go:19] FLAG: --ntp-server="0.pool.ntp.org"
I0222 21:55:23.923559       1 logs.go:19] FLAG: --secure-addr=":8443"
I0222 21:55:23.923563       1 logs.go:19] FLAG: --stderrthreshold="0"
I0222 21:55:23.923568       1 logs.go:19] FLAG: --tls-ca-file="/etc/guard/pki/ca.crt"
I0222 21:55:23.923573       1 logs.go:19] FLAG: --tls-cert-file="/etc/guard/pki/tls.crt"
I0222 21:55:23.923577       1 logs.go:19] FLAG: --tls-private-key-file="/etc/guard/pki/tls.key"
I0222 21:55:23.923582       1 logs.go:19] FLAG: --token-auth-file=""
I0222 21:55:23.923587       1 logs.go:19] FLAG: --v="3"
I0222 21:55:23.923593       1 logs.go:19] FLAG: --vmodule=""
F0222 22:05:29.052865       1 server.go:44] read udp 10.32.0.4:32778->207.180.204.206:123: i/o timeout
goroutine 97 [running]:
github.com/appscode/guard/vendor/github.com/golang/glog.stacks(0xc0005e6100, 0xc00030c640, 0x67, 0xa0)
	/go/src/github.com/appscode/guard/vendor/github.com/golang/glog/glog.go:766 +0xd4
github.com/appscode/guard/vendor/github.com/golang/glog.(*loggingT).output(0x28706e0, 0xc000000003, 0xc0005d5760, 0x27e047e, 0x9, 0x2c, 0x0)
	/go/src/github.com/appscode/guard/vendor/github.com/golang/glog/glog.go:717 +0x306
github.com/appscode/guard/vendor/github.com/golang/glog.(*loggingT).printDepth(0x28706e0, 0xc000000003, 0x1, 0xc000678f98, 0x1, 0x1)
	/go/src/github.com/appscode/guard/vendor/github.com/golang/glog/glog.go:646 +0x129
github.com/appscode/guard/vendor/github.com/golang/glog.(*loggingT).print(0x28706e0, 0xc000000003, 0xc000678f98, 0x1, 0x1)
	/go/src/github.com/appscode/guard/vendor/github.com/golang/glog/glog.go:637 +0x5a
github.com/appscode/guard/vendor/github.com/golang/glog.Fatal(0xc000678f98, 0x1, 0x1)
	/go/src/github.com/appscode/guard/vendor/github.com/golang/glog/glog.go:1125 +0x53
github.com/appscode/guard/server.Server.ListenAndServe.func1(0xc0009cc050, 0xc0009e6000)
	/go/src/github.com/appscode/guard/server/server.go:44 +0xe6
created by github.com/appscode/guard/server.Server.ListenAndServe
	/go/src/github.com/appscode/guard/server/server.go:41 +0xc75
```

**Comment by tamalsaha** [comment]
Are you still facing this issue?
